on:
  schedule:
    - cron: "30 5 * * *"
  pull_request:

jobs:
  interop:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        browserA:
          - chrome,unstable,notused,WebRTC-ForceDtls13/Enabled/
          - firefox,unstable,notused,
        browserB:
          - chrome,unstable,FEFD,
          - chrome,unstable,FEFC,WebRTC-ForceDtls13/Enabled/
          - firefox,unstable,FEFC,
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: sudo rm /usr/bin/chromedriver /usr/bin/geckodriver # remove preinstalled github chromedriver/geckodriver from $PATH
    - run: Xvfb :99 &
    - run: BROWSER_A=${{matrix.browserA}} BROWSER_B=${{matrix.browserB}} BVER=${{matrix.bver}} DISPLAY=:99.0 node test/download-browsers.js
    - run: BROWSER_A=${{matrix.browserA}} BROWSER_B=${{matrix.browserB}} BVER=${{matrix.bver}} DISPLAY=:99.0 node_modules/.bin/jest --retries=3 test/interop/
